name: Build and Push Docker Images

on:
  release:
    types: [published]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [frontend, backend]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/memory-snap-${{ matrix.component }}:${{ github.ref_name }}
          echo "Building and pushing $IMAGE_NAME"
          docker build -t $IMAGE_NAME ./${{ matrix.component }}
          docker push $IMAGE_NAME
